### ISSUE TITLE
Adapt to 7.0 changes

### ISSUE THREAD

**Issue by cdlm** [Uko/Renraku#13]
With Calypso in Pharo 7.0 I'm getting `#packageManifestOrNil was sent to nil` exceptions whenever I save methods…

> *Yuriy Tymchuk:* looks like it is a bug in Renraku that got uncovered because of the changes in Manifest

**Comment by Uko** [comment]
This should be fixed upon pharo-project/pharo#167 integration

**Comment by Uko** [comment]
Ok, the pull request was integrated. This should not happen in the new version if Pharo 7 anymore
